const END_POINTS = {
  REGISTER_USER : 'api/user/signup',
  LOGIN_USER : 'api/user/login',
  LOGIN_ADMIN : 'api/admin/login',
  SEND_OTP : 'api/user/send-otp',
  VERIFY_OTP : 'api/user/verify-otp',
  REGISTER_TRAINER : 'api/trainer/register',
  LOGIN_TRAINER : 'api/trainer/login',
  GET_TRAINERS_VERIFICATION_LIST : 'api/admin/get-pending-trainer-verification',
  SEND_ACCEPTANCE_MAIL: 'api/admin/sent-accepted-mail',
  SEND_REJECTED_MAIL : 'api/admin/send-rejected-mail',
  GET_USERS_LIST : 'api/admin/get-all-users',
  GOOGLE_LOGIN_USER : 'api/user/login-with-google',
  ADD_COURSE : 'api/trainer/add-course',
  GET_ALL_COURSES : 'api/trainer/getAll-courses',
  LIST_UNLIST : 'api/trainer/update-courseList-status',
  DELETE_COURSE: 'api/trainer/delete-course',
  ADD_CHAPTER: 'api/trainer/add-chapter',
  GET_CHAPTER_BY_COURSE_ID: 'api/trainer/get-chapter-by-courseId',
  DELETE_CHAPTER_BY_ID : 'api/trainer/delete-chapterById',
  BLOCK_UNBLOCK_USER : 'api/admin/user-block-unblock',
  GET_ALL_COURSES_ADMIN : 'api/admin/get-all-courses',
  LIST_UNLIST_COURSE_ADMIN : 'api/admin/list-unlist-course',
  GET_ALL_PROGRAMS : 'api/user/get-weight-gain-programs',
  GET_PROGRAM_DETAILS_BY_ID : 'api/user/get-programDetailsById',
  CREATE_CHECKOUT_SESSION : 'api/user/create-checkout-session',
  GET_USER_DETAILS_BY_TOKEN : 'api/user/get-user-deatilsByToken',
  GET_ENROLLED_PROGRAMS : 'api/user/get-enrolled-program',
  CHANGE_PROFILE_IMAGE: 'api/user/change-profile-image',
  MARK_VIDEO_AS_WATCHED : 'api/user/mark-video-as-watched',
  GET_PROGRAM_PROGRESS : 'api/user/get-program-progress',
  POST_NEW_COMMENT : 'api/user/post-new-comment',
  GET_ALL_COMMENTS : 'api/user/get-all-comments-for-video',
  GET_ALL_NOTIFICATIONS : 'api/trainer/get-all-notification',
  REPLAY_TO_COMMENT : 'api/trainer/replay-to-comment',
  GET_NOTIFICATION_COUNT : 'api/trainer/get-notification-count',
  MARK_NOTIFICATION_AS_READ : 'api/trainer/mark-notification-as-read',
  GET_ENROLLMENTS_DATA : 'api/trainer/get-enrollments-data',
  CREATE_CHAT_ROOM : 'api/user/create-chat-room',
  ALL_CHAT_LIST : 'api/user/get-all-chat-list',
  GET_CHAT_DETAILS : 'api/user/get-chat-details',
  SEND_NEW_MESSAGE_FROM_USER : 'api/user/send-new-message',
  SEND_IMAGE_FILE_AS_MESSAGE : 'api/user/send-image-AsMessage',
  GET_CHATLIST_FOR_TRAINER : 'api/trainer/get-chat-list',
  GET_CHAT_DETAILS_TRAINER : 'api/trainer/get-chat-details',
  SEND_NEW_MESSAGE_TRAINER : 'api/trainer/send_new_message',
  SEND_IMAGE_FILE_TRAINER : 'api/trainer/send-image-file',
  GET_REVENUE_BY_PROGRAM : 'api/trainer/get-revenue-by-program'
 }

export default END_POINTS